### ISSUE TITLE
Pi gives error CXXABI_1.3.9 not found (and 2 more)

### ISSUE THREAD

**Issue by zanco** [ogre/habdec#1]
Hi,
''''pi@pitsatwork:~/habdec_RaspberryPi $ ./habdecWebsocketServer --help
./habdecWebsocketServer: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./habdecWebsocketServer)
./habdecWebsocketServer: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./habdecWebsocketServer)
./habdecWebsocketServer: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./habdecWebsocketServer)
''''

This seems after some googling to point to GCC 5.x being required but apt-cache list only gives gcc up to 4.9 

Any help on this ?

Pi 2 B+ with Jessie headless

Thanks,
Ben

**Comment by michalfratczak** [comment]
THe binary was build on raspbian "strech". I tried building it on "wheezy" too but I could not even compile CMake. So, probably you need to update your OS, or builidng newer version of GCC

**Comment by zanco** [comment]
Thanks for fast reply. Estimated build time for newer GCC is 6 to 8 hours. Estimated upgrade time to Stretch is about 2 hours. So I took my chances ;-)

Remind me to clone the SD card after finishing.... I have 3 Pi 2B 's

Kind regards,
Ben

**Comment by zanco** [comment]
Now with Stretch I fail at rtlsdr module for Soapy installation.
collect2: error: ld returned 1 exit status
CMakeFiles/rtlsdrSupport.dir/build.make:174: recipe for target 'librtlsdrSupport.so' failed
make[2]: *** [librtlsdrSupport.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rtlsdrSupport.dir/all' failed
make[1]: *** [CMakeFiles/rtlsdrSupport.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


Any idea ?

Thanks,
Ben

**Comment by michalfratczak** [comment]
You also need SoapySDR. I think there are no prebuild bins for raspi, you have to build it from source. SoapySDR builds fast and without problems, should not take much time. Take a look into BuildInstructions.md

**Comment by michalfratczak** [comment]
Turns out Soapy is available, just do 
`sudo apt search Soapy`
and pick your modules, ie:
`sudo apt install libsoapysdr0.5-2`
`sudo apt install soapysdr-module-rtlsdr`

**Comment by michalfratczak** [comment]
Actually, don't use standard packages, or you will have performance problems.
Build from source or get prepared PI image from wiki.
