### ISSUE TITLE
HabHub Retirement

### ISSUE THREAD

**Issue by darksidelemm** [ogre/habdec#11]
HabHub will be shutting down imminently - refer here: https://github.com/projecthorus/sondehub-amateur-tracker/wiki/Guide-for-HabHub-Users
The replacement will be Sondehub-Amateur - https://amateur.sondehub.org/ which has a different interface.
While there is no UKHAS parser within Sondehub-Amateur, we accept telemetry in [this format](https://github.com/projecthorus/sondehub-infra/wiki/%5BDRAFT%5D-Amateur-Balloon-Telemetry-Format), and there are already a number of [RTTY reception options](https://github.com/projecthorus/sondehub-amateur-tracker/wiki/Receiving-High-Altitude-Balloon-Telemetry#rtty-ukhas-format-telemetry) which perform basic parsing of UKHAS-format telemetry and upload the parsed telemetry to Sondehub-Amateur, as is done by Horus-GUI/horusdemodlib.

It would be great if habdec was updated to support this as well!

**Comment by michalfratczak** [comment]
Implemented in c5a70415270b1d5c3812cffe2f3fba281cbce004
