### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by ok1iuo** [ogre/habdec#12]
I cold't  build habdec on raspbbery pi 3b 32bit 

/usr/bin/ld: CMakeFiles/habdecWebsocketServer.dir/habdec_ws_protocol.cpp.o: undefined reference to symbol '__atomic_load_8@@LIBATOMIC_1.0'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [websocketServer/CMakeFiles/habdecWebsocketServer.dir/build.make:337: websocketServer/habdecWebsocketServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:364: websocketServer/CMakeFiles/habdecWebsocketServer.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
root@raspberrypi:~/habdec/build#

**Comment by michalfratczak** [comment]
Uncomment this line
https://github.com/ogre/habdec/blob/7ac670409bd38822c088f1ca211e6640bbe7cc9b/code/websocketServer/CMakeLists.txt#L85

**Comment by michalfratczak** [comment]
I hope this solved your problem.
