### ISSUE TITLE
Cannot connect to Pi from webbrowser (Pi3 image)

### ISSUE THREAD

**Issue by zanco** [ogre/habdec#2]
Hi, downloaded the Pi3 image, but when trying to connect to the webclient I get this error

Error: boost::system::system_error: The WebSocket handshake Connection field is missing the upgrade token
Session END.

My command to start 
 ./habdecWebsocketServer --sampling_rate 1.024e+06 --rtty 75 7 1 --port 192.168.0.101:5555

**Comment by michalfratczak** [comment]
Did you start the code/webClient/index.html and connect with that? Your
error suggests you try to connect directly to http://192.168.0.101:5555

sob., 17 lis 2018, 12:01: Ben aka PE2BZ <notifications@github.com>
napisał(a):

**Comment by zanco** [comment]
HI, indeed I did try to connect to :5555 with no extension.

Now I try http://192.168.0.101:5555/code/webClient/index.html is that the one to use ? I get the same error message.

Kind regards,
Ben

**Comment by michalfratczak** [comment]
No,just open the local file index.html It is located in repo/code/webClient
When the page loads, put ip and port into server field

sob., 17 lis 2018, 12:42: Ben aka PE2BZ <notifications@github.com>
napisał(a):

**Comment by zanco** [comment]
Hi, that means I cannot do that because my Pi3 is running headless ?

**Comment by michalfratczak** [comment]
You can do this on any machine that can reach your Pi over specific ip:port
I was using it even on my phone

sob., 17 lis 2018, 13:27: Ben aka PE2BZ <notifications@github.com>
napisał(a):

**Comment by zanco** [comment]
Thanks a lot Michal,
I was assuming I could point the webbrowser to the url but I have to use a filebrowser to the share on the Pi and open the index.html from there. It looks great now ! AFC does a nice job !

**Comment by michalfratczak** [comment]
Just to sum up. You can put webClient anywhere, it does not have to be on
pi share.
Have fun!

sob., 17 lis 2018, 14:02: Ben aka PE2BZ <notifications@github.com>
napisał(a):

**Comment by michalfratczak** [comment]
Updated README.md to reflect on this issue - hopefully this is clearer now.
Closing.
