### ISSUE TITLE
Missing the ppm setting for rtl-sdr dongels ?

### ISSUE THREAD

**Issue by zanco** [ogre/habdec#3]
Hi,
I have the HabDec running now, it decodes RTTY from my local tracker :-)

I am missing a ppm option for the rtl dongle, I have a +38 ppm offset and with AFC enabled the dongle appears to tune to the signal but it misses  the first characters.

If the decode succeeds the vehicle gets reported on the map :-)

Can you add the option --ppm please ?

Thanks,
Ben

**Comment by michalfratczak** [comment]
--ppm flag has been implemented. Please upgrade and rebuild.
Report if it works not as expected.

**Comment by zanco** [comment]
HI, I did follow the update instructions on the PI3 image txt file. Updated without errors.
Tried 2 ways to set the ppm value,
first I did add ppm = 38 to the .opts file but no message about the ppm value and no change in frequency, after that I did start habdeckWebsocketServer --ppm 38 --config bz.opts but that also does not affect the ppm difference in frequency.

> Reading config from file bz.opts
Failed loading payload
Found Rafael Micro R820T tuner

Available devices:
0:
        available Yes
        driver rtlsdr
        label Generic RTL2832U OEM :: 00000001
        manufacturer Realtek
        product RTL2838UHIDIR
        rtl 0
        serial 00000001
        tuner Rafael Micro R820T
Found Rafael Micro R820T tuner
        Sampling Rates:
                250,000
                1.024e+06
                1.536e+06
                1.792e+06
                1.92e+06
                2.048e+06
                2.16e+06
                2.56e+06
                2.88e+06
                3.2e+06


Running with rtlsdr

IQSource_SoapySDR::init
        driver_key RTLSDR
Exact sample rate is: 1792000.030382 Hz
[R82XX] PLL not locked!
[INFO] Using format CF32.
        hw_key R820T
        device_id 0
        serial 00000001
        Gains:  TUNER,
        Gain Range: 0 49.6
        Freq Range: 2.3999e+07 1.764e+09
        Sampling Ranges: 250,000, 1.024e+06, 1.536e+06, 1.792e+06, 1.92e+06, 2.048e+06, 2.16e+06, 2.56e+06, 2.88e+06, 3.2e+06,
        Stream Formats: CS8, CS16, CF32,
        Frontend mapping:
        Bandwidths:
        Has DC Offset: 0
        Has Freq Correction: 1
Setting sampling_rate_double = 1.024e+06
Set sampling_rate_double = 1.024e+06
FirFilter::LP_BlackmanHarris No Input set.
FirFilter::LP_BlackmanHarris No Input set.
Current Options:
        device: 0
        sampling_rate: 1.024e+06
        command_host: 0.0.0.0
        command_port: 5,555
        sentence_cmd:
        payload:
        station: PE2BZ-HABDEC
        latlon: 52 4.2
        freq: 4.34388e+08
        gain: 15
        live_print: 1
        baud: 75
        rtty_ascii_bits: 7
        rtty_ascii_stops: 1
        biast: 0
Start DECODER_FEED_THREAD

I did copy the html and files from the Pi, opened it in the brower, but also no sign of a ppm setting.
New Client
Command cmd::get:frequency
Command cmd::get:sampling_rate
Command cmd::get:gain
Command cmd::get:baud
Command cmd::get:rtty_bits
Command cmd::get:rtty_stops
Command cmd::get:lowpass_bw
Command cmd::get:lowpass_trans
Command cmd::get:biastee
[WARNING] Unknown setting 'biastee'
Command cmd::get:decimation
Command cmd::get:afc


Am I doing something wrong ?

Thanks,
Ben
