### ISSUE TITLE
libboost version required

### ISSUE THREAD

**Issue by alexmyczko** [ogre/habdec#4]
it'll only work with 1.68 not 1.67? what about 1.69?

**Comment by michalfratczak** [comment]
boost 1.68 is what I tested with, but you should be fine with whatever version provides boost beast.
I think it's available since 1.66

**Comment by alexmyczko** [comment]
Strange, I do have: `locate beast/core.hpp`
`/usr/include/boost/beast/core.hpp`
with
`libboost1.67-dev:amd64: /usr/include/boost/beast/core.hpp`

However I get this build log (it wouldn't be found):
http://phd-sid.ethz.ch/debian/habdec/habdec_0%2Bgit20190404-1_amd64.build

**Comment by michalfratczak** [comment]
What was the exact command line for cmake invocation?
Did you pass -D BOOST_ROOT=/path/to/boost_1.68 ?
I can also see that FFTW Lib:FFTW3f_LIBRARIES-NOTFOUND. Did you pass -D FFTW_ROOT=/path/to/fftwf/install ?

If you wan't to use system-wide boost, then you have to edit [https://github.com/ogre/habdec/blob/master/code/websocketServer/CMakeLists.txt#L15](websocketServer/CMakeLists.txt) and remove 
`set ( Boost_NO_SYSTEM_PATHS ON )`
Possibly change other boost setting - sadly I'm no expert in cmake.

There is also possibility (not much) that your specific CMake 3.13 version can't handle boost 1.67.
Generally you need to make sure that CMake's FindBoost module is compatible with your boost version.
(CMake 3.12.3 is fine for boost 1.68)

**Comment by alexmyczko** [comment]
Cool thanks, that helped for blast, now I'm stuck at:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FFTW3f_LIBRARIES
    linked by target "Decoder" in directory /var/www/debian/habdec/habdec-0+git20190404/code/Decoder
```

**Comment by michalfratczak** [comment]
Similar to above. Did you pass `-D FFTW_ROOT=/path/to/fftwf/install` to cmake ?
Mind that HabDec needs FFTW compiled for floats and default FFTW configure is for doubles - so if you're using system installed FFTW it might not work (even if CMake finds it).
I recommend building FFTW as described in (https://github.com/ogre/habdec/blob/master/BuildInstructions.md) - it won't take long to build :)

**Comment by alexmyczko** [comment]
Shiny new Debian packages (might work with Ubuntu as well, built from the debian source package):

http://phd-sid.ethz.ch/debian/habdec/

It's not quite installing to the right place yet, but I'll get that fixed as well:

```
$ dpkg -L habdec
/.
/usr
/usr/habLogger.py
/usr/habdecWebsocketServer
/usr/habdec_fltk
/usr/run_loop.sh
/usr/share
/usr/share/doc
/usr/share/doc/habdec
/usr/share/doc/habdec/README.Debian
/usr/share/doc/habdec/changelog.Debian.gz
/usr/share/doc/habdec/copyright
```

**Comment by michalfratczak** [comment]
nice !

**Comment by alexmyczko** [comment]
thanks, no i already closed it.
