### ISSUE TITLE
optional fltk part

### ISSUE THREAD

**Issue by alexmyczko** [ogre/habdec#5]
I wasn't able to figure out with which version of fltk it should work. 
Did you build it with 1.1 or 1.3?

**Comment by michalfratczak** [comment]
`fltk-config --version` shows 1.3.4 
Let me say that fltk_GUI is of not much use for end user, this was an aid in debuging.
To run it, you need to pass rtty params on command line, ie:
`./habdec_fltk 300 8 2`

**Comment by alexmyczko** [comment]
I see, so I should leave it away. there's no -h option, and it crashes without parameters.

```
$ habdec_fltk 300 8 2
File: 
RADIO
No SoapySDR devices found. Exit.
X_ChangeProperty: BadValue (integer parameter out of range for operation) 0x0
Segmentation fault
```

I have an rtlsdr as device 1 (dev 0 is used for something else), for reference:
```
$ lsusb |grep -i realt
Bus 002 Device 005: ID 0bda:2832 Realtek Semiconductor Corp. RTL2832U DVB-T
Bus 001 Device 006: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

**Comment by michalfratczak** [comment]
Just leave it :) 
As to device enumeration: numbers have nothing to do with USB, it is related to 
`SoapySDR::KwargsList device_list = SoapySDR::Device::enumerate();`
For insight, take a look here: 
https://github.com/ogre/habdec/blob/master/code/websocketServer/main.cpp#L49
