### ISSUE TITLE
Windows build appears to require debug DLLs.

### ISSUE THREAD

**Issue by darksidelemm** [ogre/habdec#7]
It appears that the habdec windows binaries were built as a 'debug' build, not a 'release' build - this means that users require Visual Studio to be installed, not just the Visual C++ runtimes.

This manifests as an error on startup: "This program can't start because ucrtbased.dll is missing from your computer". The 'd' at the end of the filename indicates that this is a dll for a debug build, not a release build.

**Comment by michalfratczak** [comment]
https://github.com/ogre/habdec/wiki
Updated bins for all platforms to latest version (e524932a950f51953e6e012a0b2b01f57b18a12a)
Windows build should be 'Release' now - does that work for you ?

**Comment by darksidelemm** [comment]
Yes, that appears to start now (and lists SDR devices)! Haven't done any further testing, but that resolves the main issue. Thanks!
