### ISSUE TITLE
Control antenna rotator trough hamlib

### ISSUE THREAD

**Issue by ok1cdj** [ogre/habdec#9]
Hi, is it possible to do some script wich take postion of HAB and calculate direction and send it to `rotctld` by network ?
Same functionality is in DL-FLDigi.

Have a nice day.

Regards, Ondra

**Comment by michalfratczak** [comment]
Hey Ondra !
I have no experience with rotctld, but looking at examples this seems fairly easy to do.
`echo "\set_pos 135.0 30.0" | nc -w 1 localhost 4533`

HabDec itself has two methods to communicate with external world.

One method is using a `--sentence_cmd ./some_rot_script.sh` flag with a script to read decoded sentence and talk to rotcltd.
There are two example scripts in https://github.com/ogre/habdec/tree/master/code/habLogger

Another method is connecting to HabDec with webSocket, listening to decoded sentences and talk to rotctld. There is a simple python example for this: https://github.com/ogre/habdec/blob/master/code/pyClient/simple_listener.py

So the real work to do is to extract Lat/Lon/Alt from a sentence, calculating azimuth/elev, and sending that to rotor.
HabDec itself does not really care about structure of the sentence, so to properly extract Lat/Lon one needs to know it's position in sentence and format (decimal vs NMEA). Actually there's some code for this inside repo and I also have some script snippets around to help with this.

As I don't have any rotor around I wouldn't be able to test this properly, but I can help any other way.

**Comment by ok1cdj** [comment]
Hi Michal, thank you for answer and i will try to do some script.

Regards, Ondra

**Comment by michalfratczak** [comment]
https://gist.github.com/ogre/5c9000cf6a5a89e0a83ca05ed33a1e6e

This is a skeleton for such a script. Connects to HabDec and extracts lat/lon/alt from decoded sentences (based on Habitat info for particular callsign). 
ToDo: calculate azimuth/elev from antenna towards balloon and talk to rotor.

Let me know if you ever make this work !

Closing for now, feel free to reopen if you have any quiestions.
